CREATE TABLE IF NOT EXISTS house_prices (
    id INTEGER,
    date DATE,
    price INTEGER,
    bedrooms INTEGER,
    bathrooms FLOAT,
    sqft_living INTEGER,
    sqft_lot INTEGER,
    floors FLOAT,
    waterfront INTEGER,
    view INTEGER,
    condition INTEGER,
    grade INTEGER,
    sqft_above INTEGER,
    sqft_basement INTEGER,
    yr_built INTEGER,
    yr_renovated INTEGER,
    zipcode INTEGER,
    lat FLOAT,
    long FLOAT,
    sqft_living15 INTEGER,
    sqft_lot15 INTEGER
);